//! AI ignore file synthesizer (`fv init aiignore`).
//!
//! Generates `.claudeignore`, `.cursorignore`, and `.aiderignore` files with a
//! curated skip list so AI coding agents don't burn context on `node_modules`,
//! build artifacts, lockfiles, and binary blobs.
//!
//! Re-running the command is idempotent: only the region between the
//! `# === fv-managed start ===` / `# === fv-managed end ===` markers is
//! rewritten, so user-added rules are preserved.

use std::fs;
use std::path::{Path, PathBuf};
use std::str::FromStr;

const MARKER_START: &str = "# === fv-managed start ===";
const MARKER_END: &str = "# === fv-managed end ===";

/// Target AI agent for ignore file generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AiIgnoreAgent {
    Claude,
    Cursor,
    Aider,
}

impl AiIgnoreAgent {
    pub fn filename(&self) -> &'static str {
        match self {
            Self::Claude => ".claudeignore",
            Self::Cursor => ".cursorignore",
            Self::Aider => ".aiderignore",
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Claude => "claude",
            Self::Cursor => "cursor",
            Self::Aider => "aider",
        }
    }

    /// Default set: all three agents.
    pub fn all() -> Vec<Self> {
        vec![Self::Claude, Self::Cursor, Self::Aider]
    }
}

impl FromStr for AiIgnoreAgent {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_lowercase().as_str() {
            "claude" => Ok(Self::Claude),
            "cursor" => Ok(Self::Cursor),
            "aider" => Ok(Self::Aider),
            other => Err(format!("unknown agent: {}", other)),
        }
    }
}

/// Result of synthesizing one ignore file.
#[derive(Debug, Clone)]
pub struct SynthesisOutcome {
    pub path: PathBuf,
    pub agent: AiIgnoreAgent,
    /// Final file content (always returned for dry-run callers).
    pub content: String,
    /// Whether the file was written to disk.
    pub written: bool,
    /// Whether the on-disk content actually changed (false when idempotent).
    pub changed: bool,
}

/// Built-in skip list, language-agnostic.
///
/// Kept intentionally small. Edge cases (workspace members, monorepo dist
/// directories, etc.) are caught by the recursive nature of these glob-like
/// patterns rather than per-repo introspection.
fn builtin_patterns() -> Vec<&'static str> {
    vec![
        "# Dependencies",
        "node_modules/",
        ".pnp/",
        ".pnp.js",
        "vendor/",
        "",
        "# Build output",
        "dist/",
        "build/",
        "out/",
        "target/",
        ".next/",
        ".nuxt/",
        ".svelte-kit/",
        ".turbo/",
        ".parcel-cache/",
        "",
        "# Python",
        "__pycache__/",
        "*.pyc",
        "*.pyo",
        ".venv/",
        "venv/",
        "env/",
        ".tox/",
        ".pytest_cache/",
        ".mypy_cache/",
        ".ruff_cache/",
        "",
        "# Coverage",
        "coverage/",
        ".coverage",
        ".nyc_output/",
        "",
        "# Lockfiles (large, rarely useful for AI context)",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "Cargo.lock",
        "poetry.lock",
        "Gemfile.lock",
        "composer.lock",
        "",
        "# OS / editor",
        ".DS_Store",
        "Thumbs.db",
        ".idea/",
        ".vscode/",
        "*.swp",
        "*.swo",
        "",
        "# Secrets",
        ".env",
        ".env.*",
        "!.env.example",
        "",
        "# Logs",
        "*.log",
        "logs/",
        "",
        "# Binary blobs",
        "*.png",
        "*.jpg",
        "*.jpeg",
        "*.gif",
        "*.webp",
        "*.ico",
        "*.pdf",
        "*.zip",
        "*.tar",
        "*.tar.gz",
        "*.tgz",
        "*.7z",
        "*.parquet",
        "*.sqlite",
        "*.db",
        "",
        "# Generated",
        "*.generated.*",
        "*.gen.*",
        "*.min.js",
        "*.min.css",
    ]
}

fn header_for(agent: AiIgnoreAgent) -> String {
    format!(
        "# Auto-generated by `fv init aiignore` ({} agent).\n# Edit lines outside the markers; the block between them is rewritten on each run.",
        agent.as_str()
    )
}

/// Build the managed block (markers included) for one agent.
pub fn managed_block(agent: AiIgnoreAgent) -> String {
    let mut out = String::new();
    out.push_str(MARKER_START);
    out.push('\n');
    out.push_str(&header_for(agent));
    out.push('\n');
    for line in builtin_patterns() {
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(MARKER_END);
    out.push('\n');
    out
}

/// Merge `block` (already wrapped in markers) into `existing`.
///
/// - If markers are present, the region between them is replaced.
/// - Otherwise, the block is appended (with a blank line separator if the
///   existing file is non-empty).
pub fn merge_block(existing: &str, block: &str) -> String {
    if let (Some(start), Some(end)) = (existing.find(MARKER_START), existing.find(MARKER_END)) {
        let end_line_end = existing[end..]
            .find('\n')
            .map(|i| end + i + 1)
            .unwrap_or(existing.len());
        let mut out = String::with_capacity(existing.len() + block.len());
        out.push_str(&existing[..start]);
        out.push_str(block);
        if end_line_end < existing.len() {
            out.push_str(&existing[end_line_end..]);
        }
        return out;
    }

    let mut out = String::with_capacity(existing.len() + block.len() + 2);
    out.push_str(existing);
    if !existing.is_empty() && !existing.ends_with('\n') {
        out.push('\n');
    }
    if !existing.is_empty() {
        out.push('\n');
    }
    out.push_str(block);
    out
}

/// Synthesize ignore files for the given agents under `root`.
///
/// - `write = false`: dry-run; returns the would-be content but writes nothing.
/// - `force = true`: even when on-disk content already matches, rewrite the file
///   (mostly useful for tests or to refresh after a marker was hand-edited).
pub fn synthesize(
    root: &Path,
    agents: &[AiIgnoreAgent],
    write: bool,
    force: bool,
) -> anyhow::Result<Vec<SynthesisOutcome>> {
    if agents.is_empty() {
        anyhow::bail!("no agents specified");
    }

    let mut outcomes = Vec::with_capacity(agents.len());

    for agent in agents {
        let path = root.join(agent.filename());
        let block = managed_block(*agent);

        let existing = if path.exists() {
            fs::read_to_string(&path)
                .map_err(|e| anyhow::anyhow!("failed to read {}: {}", path.display(), e))?
        } else {
            String::new()
        };

        let merged = merge_block(&existing, &block);
        let changed = merged != existing;

        let written = if write && (changed || force) {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|e| anyhow::anyhow!("failed to create {}: {}", parent.display(), e))?;
            }
            fs::write(&path, &merged)
                .map_err(|e| anyhow::anyhow!("failed to write {}: {}", path.display(), e))?;
            true
        } else {
            false
        };

        outcomes.push(SynthesisOutcome {
            path,
            agent: *agent,
            content: merged,
            written,
            changed,
        });
    }

    Ok(outcomes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn agent_from_str_accepts_known_names() {
        assert_eq!(
            AiIgnoreAgent::from_str("claude").unwrap(),
            AiIgnoreAgent::Claude
        );
        assert_eq!(
            AiIgnoreAgent::from_str("CURSOR").unwrap(),
            AiIgnoreAgent::Cursor
        );
        assert_eq!(
            AiIgnoreAgent::from_str("aider").unwrap(),
            AiIgnoreAgent::Aider
        );
        assert!(AiIgnoreAgent::from_str("openai").is_err());
    }

    #[test]
    fn managed_block_contains_markers_and_core_patterns() {
        let block = managed_block(AiIgnoreAgent::Claude);
        assert!(block.starts_with(MARKER_START));
        assert!(block.contains(MARKER_END));
        assert!(block.contains("node_modules/"));
        assert!(block.contains("target/"));
        assert!(block.contains("__pycache__/"));
    }

    #[test]
    fn merge_block_appends_when_no_markers() {
        let existing = "*.bak\n";
        let block = managed_block(AiIgnoreAgent::Cursor);
        let merged = merge_block(existing, &block);
        assert!(merged.starts_with("*.bak\n"));
        assert!(merged.contains(MARKER_START));
        assert!(merged.contains("node_modules/"));
    }

    #[test]
    fn merge_block_replaces_marked_region_only() {
        let user_above = "# user rule above\nlocal-only/\n";
        let user_below = "# user rule below\nsecret.txt\n";
        let initial = format!(
            "{}{}# old managed\nold-pattern/\n{}\n{}",
            user_above, MARKER_START, MARKER_END, user_below
        );
        let merged = merge_block(&initial, &managed_block(AiIgnoreAgent::Aider));

        assert!(
            merged.contains("local-only/"),
            "user rules above markers must survive"
        );
        assert!(
            merged.contains("secret.txt"),
            "user rules below markers must survive"
        );
        assert!(
            !merged.contains("old-pattern/"),
            "old managed region must be replaced"
        );
        assert!(
            merged.contains("node_modules/"),
            "new managed region must be present"
        );
    }

    #[test]
    fn synthesize_dry_run_writes_nothing() {
        let dir = tempdir().unwrap();
        let outcomes = synthesize(dir.path(), &AiIgnoreAgent::all(), false, false).unwrap();
        assert_eq!(outcomes.len(), 3);
        for o in &outcomes {
            assert!(!o.written);
            assert!(!o.path.exists());
            assert!(o.changed, "fresh file should be reported as changed");
        }
    }

    #[test]
    fn synthesize_writes_three_files_when_requested() {
        let dir = tempdir().unwrap();
        let outcomes = synthesize(dir.path(), &AiIgnoreAgent::all(), true, false).unwrap();
        for o in outcomes {
            assert!(o.written);
            assert!(o.path.exists());
            let on_disk = fs::read_to_string(&o.path).unwrap();
            assert!(on_disk.contains("node_modules/"));
            assert!(on_disk.contains(MARKER_START));
        }
    }

    #[test]
    fn synthesize_is_idempotent_on_second_run() {
        let dir = tempdir().unwrap();
        let agents = AiIgnoreAgent::all();
        let _ = synthesize(dir.path(), &agents, true, false).unwrap();
        let second = synthesize(dir.path(), &agents, true, false).unwrap();
        for o in second {
            assert!(!o.changed, "second run must report no changes");
            assert!(!o.written, "second run must not rewrite");
        }
    }

    #[test]
    fn synthesize_preserves_user_lines_outside_markers() {
        let dir = tempdir().unwrap();
        let path = dir.path().join(".claudeignore");
        fs::write(&path, "# user header\nmy-secret.json\n").unwrap();

        let _ = synthesize(dir.path(), &[AiIgnoreAgent::Claude], true, false).unwrap();

        let on_disk = fs::read_to_string(&path).unwrap();
        assert!(on_disk.contains("my-secret.json"));
        assert!(on_disk.contains(MARKER_START));
        assert!(on_disk.contains("node_modules/"));
    }

    #[test]
    fn synthesize_force_rewrites_even_when_unchanged() {
        let dir = tempdir().unwrap();
        let agents = vec![AiIgnoreAgent::Claude];
        let _ = synthesize(dir.path(), &agents, true, false).unwrap();
        let forced = synthesize(dir.path(), &agents, true, true).unwrap();
        for o in forced {
            assert!(o.written, "force=true must rewrite");
            assert!(!o.changed, "content didn't change, only the write happened");
        }
    }

    #[test]
    fn synthesize_rejects_empty_agent_list() {
        let dir = tempdir().unwrap();
        let err = synthesize(dir.path(), &[], false, false).unwrap_err();
        assert!(err.to_string().contains("no agents"));
    }
}
